services:
  Backend.Planting.domain.PlantingRepository:
    class: ../../../../Contexts/Planting/infrastructure/persistence/PostgresPlantingRepository
    arguments: ['@Backend.Shared.PostgresConnection', '@Backend.Shared.PostgresGarderingConfig']

  Backend.Planting.application.PlantingCreator:
    class: ../../../../Contexts/Planting/application/Create/PlantingCreator
    arguments: 
      ['@Backend.Planting.domain.PlantingRepository', '@Backend.Task.domain.TaskRepository', '@Backend.Task.application.TaskGenerator']

  Backend.Planting.application.CreatePlantingCommandHandler:
    class: ../../../../Contexts/Planting/application/Create/CreatePlantingCommandHandler
    arguments: ['@Backend.Planting.application.PlantingCreator']
    tags:
      - { name: 'commandHandler' }

  Backend.Planting.application.PlantingByIdFinder:
    class: ../../../../Contexts/Planting/application/FindPlantingById/PlantingByIdFinder
    arguments: ['@Backend.Planting.domain.PlantingRepository']

  Backend.Planting.application.FindPlantingByIdQueryHandler:
    class: ../../../../Contexts/Planting/application/FindPlantingById/FindPlantingByIdQueryHandler
    arguments: ['@Backend.Planting.application.PlantingByIdFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Planting.application.PlantingsFinder:
    class: ../../../../Contexts/Planting/application/FindPlantings/PlantingsFinder
    arguments:
      ['@Backend.Planting.domain.PlantingRepository', '@Backend.Garden.domain.UserGardenRepository']

  Backend.Planting.application.FindPlantingsQueryHandler:
    class: ../../../../Contexts/Planting/application/FindPlantings/FindPlantingsQueryHandler
    arguments: ['@Backend.Planting.application.PlantingsFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Planting.application.GetPlantingStatusFinder:
    class: ../../../../Contexts/Planting/application/GetPlantingStatus/GetPlantingStatusFinder
    arguments:
      [
        '@Backend.Planting.application.PlantingByIdFinder',
        '@Backend.Crop.domain.CropRepository',
        '@Backend.Garden.domain.UserGardenRepository'
      ]

  Backend.Planting.application.GetPlantingStatusQueryHandler:
    class: ../../../../Contexts/Planting/application/GetPlantingStatus/GetPlantingStatusQueryHandler
    arguments: ['@Backend.Planting.application.GetPlantingStatusFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Planting.application.CropHarvester:
    class: ../../../../Contexts/Planting/application/Harvest/CropHarvester
    arguments: ['@Backend.Planting.domain.PlantingRepository']

  Backend.Planting.application.HarvestCropCommandHandler:
    class: ../../../../Contexts/Planting/application/Harvest/HarvestCropCommandHandler
    arguments: ['@Backend.Planting.application.CropHarvester']
    tags:
      - { name: 'commandHandler' }

  Backend.Planting.application.ArchivedPlantingsFinder:
    class: ../../../../Contexts/Planting/application/FindArchivedPlantings/ArchivedPlantingsFinder
    arguments:
      ['@Backend.Planting.domain.PlantingRepository', '@Backend.Crop.domain.CropRepository']

  Backend.Planting.application.FindArchivedPlantingsQueryHandler:
    class: ../../../../Contexts/Planting/application/FindArchivedPlantings/FindArchivedPlantingsQueryHandler
    arguments: ['@Backend.Planting.application.ArchivedPlantingsFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Planting.application.PlantingsByPlotFinder:
    class: ../../../../Contexts/Planting/application/FindPlantingsByPlot/PlantingsByPlotFinder
    arguments:
      ['@Backend.Planting.domain.PlantingRepository', '@Backend.Crop.domain.CropRepository', '@Backend.Plot.domain.PlotRepository']

  Backend.Planting.application.FindPlantingsByPlotQueryHandler:
    class: ../../../../Contexts/Planting/application/FindPlantingsByPlot/FindPlantingsByPlotQueryHandler
    arguments: ['@Backend.Planting.application.PlantingsByPlotFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Planting.application.PlantingAssociationsService:
    class: ../../../../Contexts/Planting/application/PlantingAssociationsService
    arguments:
      ['@Backend.Planting.infrastructure.persistence.PostgresPlantingAssociationsRepository', '@Backend.Planting.infrastructure.persistence.PostgresAssociationObservationsRepository', '@Backend.Crop.domain.CropCompatibilityRepository', '@Backend.Shared.PostgresConnection']

  Backend.Planting.infrastructure.persistence.PostgresPlantingAssociationsRepository:
    class: ../../../../Contexts/Planting/infrastructure/persistence/PostgresPlantingAssociationsRepository
    arguments: ['@Backend.Shared.PostgresConnection', '@Backend.Shared.PostgresGarderingConfig']

  Backend.Planting.infrastructure.persistence.PostgresAssociationObservationsRepository:
    class: ../../../../Contexts/Planting/infrastructure/persistence/PostgresAssociationObservationsRepository
    arguments: ['@Backend.Shared.PostgresConnection', '@Backend.Shared.PostgresGarderingConfig']
