imports:
  - { resource: ./Cronjob/application.yaml }
  - { resource: ./Crop/application.yaml }
  - { resource: ./Garden/application.yaml }
  - { resource: ./Lunar/application.yaml }
  - { resource: ./Planting/application.yaml }
  - { resource: ./Plot/application.yaml }
  - { resource: ./Task/application.yaml }
  - { resource: ./User/application.yaml }
  - { resource: ./Rotation/application.yaml }
  - { resource: ./Weather/application.yaml }
  - { resource: ./Dashboard/application.yaml }
