services:
  Backend.User.domain.UserRepository:
    class: ../../../../Contexts/User/infrastructure/persistence/PostgresUserRepository
    arguments: ['@Backend.Shared.PostgresConnection', '@Backend.Shared.PostgresGarderingConfig']

  Backend.User.application.UserCreator:
    class: ../../../../Contexts/User/application/Create/UserCreator
    arguments: ['@Backend.User.domain.UserRepository']

  Backend.User.application.UserFinder:
    class: ../../../../Contexts/User/application/FindUserById/UserByIdFinder
    arguments: ['@Backend.User.domain.UserRepository']

  Backend.User.application.CreateUserCommandHandler:
    class: ../../../../Contexts/User/application/Create/CreateUserCommandHandler
    arguments: ['@Backend.User.application.UserCreator']
    tags:
      - { name: 'commandHandler' }

  Backend.User.application.FindUserByIdQueryHandler:
    class: ../../../../Contexts/User/application/FindUserById/FindUserByIdQueryHandler
    arguments: ['@Backend.User.application.UserFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.User.application.Authenticator:
    class: ../../../../Contexts/User/application/Login/Authenticator
    arguments:
      [
        '@Backend.User.domain.UserRepository',
        '@Backend.Shared.PasswordHasher',
        '@Backend.Shared.JwtHandler'
      ]

  Backend.User.application.LoginQueryHandler:
    class: ../../../../Contexts/User/application/Login/LoginQueryHandler
    arguments: ['@Backend.User.application.Authenticator']
    tags:
      - { name: 'queryHandler' }

  Backend.User.application.ProfileUpdater:
    class: ../../../../Contexts/User/application/UpdateProfile/ProfileUpdater
    arguments: ['@Backend.User.domain.UserRepository', '@Backend.Shared.PasswordHasher']

  Backend.User.application.UpdateProfileCommandHandler:
    class: ../../../../Contexts/User/application/UpdateProfile/UpdateProfileCommandHandler
    arguments: ['@Backend.User.application.ProfileUpdater']
    tags:
      - { name: 'commandHandler' }

  Backend.User.application.LogoutCommandHandler:
    class: ../../../../Contexts/User/application/Logout/LogoutCommandHandler
    arguments: ['@Backend.Shared.JwtHandler']
    tags:
      - { name: 'commandHandler' }
