services:
  Backend.Rotation.controllers.GetPlotRotationHistoryController:
    class: ../../../controllers/rotation/GetPlotRotationHistoryController
    arguments: ['@Backend.Shared.PostgresConnection']
