services:
  Backend.Plot.domain.PlotRepository:
    class: ../../../../Contexts/Plot/infrastructure/persistence/PostgresPlotRepository
    arguments: ['@Backend.Shared.PostgresConnection', '@Backend.Shared.PostgresGarderingConfig']

  Backend.Plot.application.PlotCreator:
    class: ../../../../Contexts/Plot/application/CreatePlot/PlotCreator
    arguments: ['@Backend.Plot.domain.PlotRepository']

  Backend.Plot.application.AllPlotsFinder:
    class: ../../../../Contexts/Plot/application/FindAllPlots/AllPlotsFinder
    arguments: ['@Backend.Plot.domain.PlotRepository']

  Backend.Plot.application.PlotByIdFinder:
    class: ../../../../Contexts/Plot/application/FindPlotById/PlotByIdFinder
    arguments: ['@Backend.Plot.domain.PlotRepository']

  Backend.Plot.application.CreatePlotCommandHandler:
    class: ../../../../Contexts/Plot/application/CreatePlot/CreatePlotCommandHandler
    arguments: ['@Backend.Plot.application.PlotCreator']
    tags:
      - { name: 'commandHandler' }

  Backend.Plot.application.FindAllPlotsQueryHandler:
    class: ../../../../Contexts/Plot/application/FindAllPlots/FindAllPlotsQueryHandler
    arguments: 
      ['@Backend.Plot.application.AllPlotsFinder', '@Backend.Planting.domain.PlantingRepository', '@Backend.Crop.domain.CropRepository']
    tags:
      - { name: 'queryHandler' }

  Backend.Plot.application.FindPlotByIdQueryHandler:
    class: ../../../../Contexts/Plot/application/FindPlotById/FindPlotByIdQueryHandler
    arguments: ['@Backend.Plot.application.PlotByIdFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Plot.application.PlotUpdater:
    class: ../../../../Contexts/Plot/application/UpdatePlot/PlotUpdater
    arguments: ['@Backend.Plot.domain.PlotRepository']

  Backend.Plot.application.UpdatePlotCommandHandler:
    class: ../../../../Contexts/Plot/application/UpdatePlot/UpdatePlotCommandHandler
    arguments: ['@Backend.Plot.application.PlotUpdater']
    tags:
      - { name: 'commandHandler' }

  Backend.Plot.application.DeletePlotCommandHandler:
    class: ../../../../Contexts/Plot/application/DeletePlot/DeletePlotCommandHandler
    tags:
      - { name: 'commandHandler' }
