services:
  Backend.Crop.domain.CropRepository:
    class: ../../../../Contexts/Crop/infrastructure/persistence/PostgresCropRepository
    arguments: ['@Backend.Shared.PostgresConnection']

  Backend.Crop.domain.CropCompatibilityRepository:
    class: ../../../../Contexts/Crop/infrastructure/persistence/PostgresCropCompatibilityRepository
    arguments: ['@Backend.Shared.PostgresConnection']

  Backend.Crop.application.AllCropsFinder:
    class: ../../../../Contexts/Crop/application/FindAllCrops/AllCropsFinder
    arguments: ['@Backend.Crop.domain.CropRepository']

  Backend.Crop.application.CropByIdFinder:
    class: ../../../../Contexts/Crop/application/FindCropById/CropByIdFinder
    arguments: ['@Backend.Crop.domain.CropRepository']

  Backend.Crop.application.CropsByFamilyFinder:
    class: ../../../../Contexts/Crop/application/FindCropsByFamily/CropsByFamilyFinder
    arguments: ['@Backend.Crop.domain.CropRepository']

  Backend.Crop.application.CropCompatibilityFinder:
    class: ../../../../Contexts/Crop/application/FindCropCompatibilities/CropCompatibilityFinder
    arguments: ['@Backend.Crop.domain.CropCompatibilityRepository']

  Backend.Crop.application.FindAllCropsQueryHandler:
    class: ../../../../Contexts/Crop/application/FindAllCrops/FindAllCropsQueryHandler
    arguments: ['@Backend.Crop.application.AllCropsFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Crop.application.FindCropByIdQueryHandler:
    class: ../../../../Contexts/Crop/application/FindCropById/FindCropByIdQueryHandler
    arguments: ['@Backend.Crop.application.CropByIdFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Crop.application.FindCropsByFamilyQueryHandler:
    class: ../../../../Contexts/Crop/application/FindCropsByFamily/FindCropsByFamilyQueryHandler
    arguments: ['@Backend.Crop.application.CropsByFamilyFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Crop.application.FindCropCompatibilitiesQueryHandler:
    class: ../../../../Contexts/Crop/application/FindCropCompatibilities/FindCropCompatibilitiesQueryHandler
    arguments: ['@Backend.Crop.application.CropCompatibilityFinder']
    tags:
      - { name: 'queryHandler' }

  Backend.Crop.application.CropManager:
    class: ../../../../Contexts/Crop/application/Manage/CropManager
    arguments: ['@Backend.Crop.domain.CropRepository']

  Backend.Crop.application.ManageCropCommandHandler:
    class: ../../../../Contexts/Crop/application/Manage/ManageCropCommandHandler
    arguments: ['@Backend.Crop.application.CropManager']
    tags:
      - { name: 'commandHandler' }

  Backend.Crop.application.CropDeleter:
    class: ../../../../Contexts/Crop/application/Delete/CropDeleter
    arguments: ['@Backend.Crop.domain.CropRepository']

  Backend.Crop.application.DeleteCropCommandHandler:
    class: ../../../../Contexts/Crop/application/Delete/DeleteCropCommandHandler
    arguments: ['@Backend.Crop.application.CropDeleter']
    tags:
      - { name: 'commandHandler' }
